#######################################################################################
# Book settings
title : IPC
author: Margarida Madeira e Moura
logo: 'IPC_wc.png'

# Information about where the book exists on the web
description: >-
  Introdução à Programação Científica para Bioengenharia.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
# Information about where the book exists on the web
repository:
  url                       : https://margaridamadeira.github.io/IPC-2020-21
  path_to_book              : docs  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

binder:
  binderhub_url               : "https://mybinder.org/v2/gh/margaridamadeira/IPC-2020-21/master"
  text                        : "Launch binder"

launch_buttons:
  notebook_interface          : "classic"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
